/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feereportproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ABC
 */
public class AdminSection extends javax.swing.JFrame {

    /**
     * Creates new form AdminSection
     */
    public AdminSection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        adAdd = new javax.swing.JButton();
        adGoback = new javax.swing.JButton();
        adView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adAccname = new javax.swing.JTextField();
        adAccemail = new javax.swing.JTextField();
        adAcccontact = new javax.swing.JTextField();
        adAccpass = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        AdminTbl = new javax.swing.JTable();
        adAccsalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adViewS = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        adAccID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        adDelS = new javax.swing.JButton();
        adUpdate = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        adAdd.setBackground(new java.awt.Color(51, 51, 51));
        adAdd.setForeground(new java.awt.Color(255, 255, 255));
        adAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\AppData\\Local\\Temp\\icons8_add_new_16px_1.png")); // NOI18N
        adAdd.setText("Add Accountant");
        adAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adAddActionPerformed(evt);
            }
        });

        adGoback.setBackground(new java.awt.Color(51, 51, 51));
        adGoback.setForeground(new java.awt.Color(255, 255, 255));
        adGoback.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\AppData\\Local\\Temp\\icons8_previous_32px_2.png")); // NOI18N
        adGoback.setText("Go Back");
        adGoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adGobackActionPerformed(evt);
            }
        });

        adView.setBackground(new java.awt.Color(51, 51, 51));
        adView.setForeground(new java.awt.Color(255, 255, 255));
        adView.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\AppData\\Local\\Temp\\icons8_view_16px_1.png")); // NOI18N
        adView.setText("View Accountants");
        adView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adViewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Section");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name: ");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password: ");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email: ");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact No:");
        jLabel5.setToolTipText("");

        adAccname.setToolTipText("");

        adAccemail.setToolTipText("");

        adAcccontact.setToolTipText("Follow format: 0XXX-XXXXXXX");

        AdminTbl.setBackground(new java.awt.Color(0, 0, 0));
        AdminTbl.setForeground(new java.awt.Color(255, 255, 255));
        AdminTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        AdminTbl.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(AdminTbl);

        adAccsalary.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salary:");
        jLabel6.setToolTipText("");

        adViewS.setBackground(new java.awt.Color(51, 51, 51));
        adViewS.setForeground(new java.awt.Color(255, 255, 255));
        adViewS.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\AppData\\Local\\Temp\\icons8_eye_16px.png")); // NOI18N
        adViewS.setText("View Specific");
        adViewS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adViewSActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID:");
        jLabel7.setToolTipText("");

        adAccID.setToolTipText("Insert ID to Search");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\AppData\\Local\\Temp\\icons8_system_administrator_male_32px_3.png")); // NOI18N

        adDelS.setBackground(new java.awt.Color(51, 51, 51));
        adDelS.setForeground(new java.awt.Color(255, 255, 255));
        adDelS.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\AppData\\Local\\Temp\\icons8_close_window_16px.png")); // NOI18N
        adDelS.setText("Delete Specific");
        adDelS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adDelSActionPerformed(evt);
            }
        });

        adUpdate.setBackground(new java.awt.Color(51, 51, 51));
        adUpdate.setForeground(new java.awt.Color(255, 255, 255));
        adUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABC\\AppData\\Local\\Temp\\icons8_refresh_16px_1.png")); // NOI18N
        adUpdate.setText("Update Record");
        adUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(adGoback)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adAccname)
                            .addComponent(adAccemail)
                            .addComponent(adAcccontact)
                            .addComponent(adAccpass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adAccsalary, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(adAdd)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adAccID, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(adDelS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adUpdate)
                                .addGap(10, 10, 10)
                                .addComponent(adViewS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adView)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(adAccname)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adAccpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adAccemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adAcccontact))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adAccsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adAccID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(adDelS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(adView, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adViewS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adGobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adGobackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_adGobackActionPerformed

    private void adAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adAddActionPerformed
        // TODO add your handling code here:
        ResultSet resultSet = null;
        
        String Name = adAccname.getText().trim().toString();
        String Pass = String.valueOf(adAccpass.getPassword());
        String Email = adAccemail.getText().trim().toString();
        String Contact = adAcccontact.getText().trim().toString();
        String Salary = adAccsalary.getText().trim().toString();
        
        JFrame j = new JFrame();
        
        if(Name.equals(null))
        {
            JOptionPane.showMessageDialog(j,"Please Enter Name...");
        }
        else if(Pass.equals(null))
        {
            JOptionPane.showMessageDialog(j,"Please Enter Password...");   
        }
        else if(Email.equals(null))
        {
            JOptionPane.showMessageDialog(j,"Please Enter Email...");   
        }
        else if(Contact.equals(null))
        {
            JOptionPane.showMessageDialog(j,"Please Enter Contact Number...");   
        }
        else
        {   
            try
            {
                String connectionUrl="jdbc:sqlserver://RASIKH-LAPTOP:1433;databaseName=Fee_Report;IntegratedSecurity=true";
                Connection connection = DriverManager.getConnection(connectionUrl);
                System.out.println("Connection Successful");

                String sql = "insert into Accountant_Rec([Name], [Password], Email, Contact, Salary) values( ?, ?, ?, ?, ?)";
                PreparedStatement statement  = connection.prepareStatement(sql);
                
                statement.setString(1, Name);
                statement.setString(2, Pass);
                statement.setString(3, Email);
                statement.setString(4, Contact);
                statement.setString(5, Salary);
                
                int res = statement.executeUpdate();
                
                if(res > 0)
                {
                    JOptionPane.showMessageDialog(j,"Details Inserted Successfully");
                }
                else
                {
                    JOptionPane.showMessageDialog(j,"Details Not Inserted");
                }
            }
            catch(java.sql.SQLException e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_adAddActionPerformed

    private void adViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adViewActionPerformed
        // TODO add your handling code here:
        
        ResultSet resultSet = null;
         
        try
        {
            String connectionUrl="jdbc:sqlserver://RASIKH-LAPTOP:1433;databaseName=Fee_Report;IntegratedSecurity=true";
            Connection connection = DriverManager.getConnection(connectionUrl);
            System.out.println("Connection Successful");
            
            String sql = "SELECT * from Accountant_Rec ";
            Statement  statement  = connection.createStatement();
            
            resultSet = statement.executeQuery(sql);
            AdminTbl.setModel(DbUtils.resultSetToTableModel(resultSet));
            
        }
        catch(java.sql.SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_adViewActionPerformed

    private void adViewSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adViewSActionPerformed
        // TODO add your handling code here:
        String ID = adAccID.getText().trim().toString();
        ResultSet resultSet = null;
        if(!ID.isEmpty())
        {
            try
            {
                String connectionUrl="jdbc:sqlserver://RASIKH-LAPTOP:1433;databaseName=Fee_Report;IntegratedSecurity=true";
                Connection connection = DriverManager.getConnection(connectionUrl);
                System.out.println("Connection Successful");

                String sql = "SELECT * from Accountant_Rec where ID = " + ID;
                Statement  statement  = connection.createStatement();

                resultSet = statement.executeQuery(sql);
                AdminTbl.setModel(DbUtils.resultSetToTableModel(resultSet));
            }
            catch(java.sql.SQLException e)
            {
                e.printStackTrace();
            }
        }
        else
        {
            JFrame j = new JFrame();
            JOptionPane.showMessageDialog(j,"Please Enter ID...");
        }
    }//GEN-LAST:event_adViewSActionPerformed

    private void adDelSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adDelSActionPerformed
        // TODO add your handling code here:
        String ID = adAccID.getText().trim().toString();
        ResultSet resultSet = null;
        JFrame j = new JFrame();
        if(!ID.isEmpty())
        {
            try
            {
                String connectionUrl="jdbc:sqlserver://RASIKH-LAPTOP:1433;databaseName=Fee_Report;IntegratedSecurity=true";
                Connection connection = DriverManager.getConnection(connectionUrl);
                System.out.println("Connection Successful");

                String sql = "Delete from Accountant_Rec where ID = ?";
                
                PreparedStatement statement  = connection.prepareStatement(sql);
                statement.setString(1, ID);
                
                int res = statement.executeUpdate();
                if(res > 0)
                {
                    JOptionPane.showMessageDialog(j,"Details Deleted Successfully...");
                }
                else
                {
                    JOptionPane.showMessageDialog(j,"Details Not Deleted...");
                }
            }
            catch(java.sql.SQLException e)
            {
                e.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(j,"Please Enter ID...");
        }
    }//GEN-LAST:event_adDelSActionPerformed

    private void adUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adUpdateActionPerformed
        // TODO add your handling code here:
        ResultSet resultSet = null;
        
        String Name = adAccname.getText().trim().toString();
        String Pass = String.valueOf(adAccpass.getPassword());
        String Email = adAccemail.getText().trim().toString();
        String Contact = adAcccontact.getText().trim().toString();
        String Salary = adAccsalary.getText().trim().toString();
                
        String ID = adAccID.getText().trim().toString();
        
        JFrame j = new JFrame();
        
        if(!ID.isEmpty())
        {
            try
            {
                String connectionUrl="jdbc:sqlserver://RASIKH-LAPTOP:1433;databaseName=Fee_Report;IntegratedSecurity=true";
                Connection connection = DriverManager.getConnection(connectionUrl);
                System.out.println("Connection Successful");

                String sql = "";
                
                PreparedStatement statement  = null;
                
                if(Name.equals(""))
                {
                    sql = "Update Accountant_Rec set [Password] = ?, Email = ?, Contact = ?, Salary = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Pass);
                    statement.setString(2, Email);
                    statement.setString(3, Contact);
                    statement.setString(4, Salary);
                    statement.setInt(5, Integer.valueOf(ID));
                }
                if(Name.equals("") && Pass.equals(""))
                {
                    sql = "Update Accountant_Rec set Email = ?, Contact = ?, Salary = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Email);
                    statement.setString(2, Contact);
                    statement.setString(3, Salary);
                    statement.setInt(4, Integer.valueOf(ID));
                }
                if(Pass.equals(""))
                {
                    sql = "Update Accountant_Rec set [Name] = ?, Email = ?, Contact = ?, Salary = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Email);
                    statement.setString(3, Contact);
                    statement.setString(4, Salary);
                    statement.setInt(5, Integer.valueOf(ID));
                }
                if(Email.equals(""))
                {
                    sql = "Update Accountant_Rec set [Name] = ?, [Password] = ?, Contact = ?, Salary = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Pass);
                    statement.setString(3, Contact);
                    statement.setString(4, Salary);
                    statement.setInt(5, Integer.valueOf(ID));
                }
                if(Contact.equals(""))
                {
                    sql = "Update Accountant_Rec set [Name] = ?, [Password] = ?, Email = ?, Salary = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Pass);
                    statement.setString(3, Email);
                    statement.setString(4, Salary);
                    statement.setInt(5, Integer.valueOf(ID));
                }
                if(Email.equals("") && Contact.equals(""))
                {
                    sql = "Update Accountant_Rec set [Name] = ?, [Password] = ?, Salary = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Pass);
                    statement.setString(3, Salary);
                    statement.setInt(4, Integer.valueOf(ID));
                }
                if(Salary.equals(""))
                {
                    sql = "Update Accountant_Rec set [Name] = ?, [Password] = ?, Contact = ?, Email = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Pass);
                    statement.setString(3, Contact);
                    statement.setString(4, Email);
                    statement.setInt(5, Integer.valueOf(ID));
                }
                if(Salary.equals("") && Contact.equals(""))
                {
                    sql = "Update Accountant_Rec set [Name] = ?, [Password] = ?, Email = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Pass);
                    statement.setString(3, Email);
                    statement.setInt(4, Integer.valueOf(ID));
                }
                if(Salary.equals("") && Email.equals(""))
                {
                    sql = "Update Accountant_Rec set [Name] = ?, [Password] = ?, Contact = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Pass);
                    statement.setString(3, Contact);
                    statement.setInt(4, Integer.valueOf(ID));
                }
                if(Salary.equals("") && Email.equals("") && Contact.equals(""))
                {
                    sql = "Update Accountant_Rec set [Name] = ?, [Password] = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Pass);
                    statement.setInt(3, Integer.valueOf(ID));
                }
                else
                {
                    sql = "Update Accountant_Rec set [Name] = ?, [Password] = ?, Contact = ?, Email = ?, Salary = ? where ID = ?";
                
                    statement  = connection.prepareStatement(sql);
                    statement.setString(1, Name);
                    statement.setString(2, Pass);
                    statement.setString(3, Contact);
                    statement.setString(4, Email);
                    statement.setString(5, Salary);
                    statement.setInt(6, Integer.valueOf(ID));
                }
                
                int res = statement.executeUpdate();
                
                if(res > 0)
                {
                    JOptionPane.showMessageDialog(j,"Details Updated Successfully...");
                }
                else
                {
                    JOptionPane.showMessageDialog(j,"Details Not Updated...");
                }
            }
            catch(java.sql.SQLException e)
            {
                e.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(j,"Please Enter ID...");
        }
    }//GEN-LAST:event_adUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AdminTbl;
    private javax.swing.JTextField adAccID;
    private javax.swing.JTextField adAcccontact;
    private javax.swing.JTextField adAccemail;
    private javax.swing.JTextField adAccname;
    private javax.swing.JPasswordField adAccpass;
    private javax.swing.JTextField adAccsalary;
    private javax.swing.JButton adAdd;
    private javax.swing.JButton adDelS;
    private javax.swing.JButton adGoback;
    private javax.swing.JButton adUpdate;
    private javax.swing.JButton adView;
    private javax.swing.JButton adViewS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
